<?php

/**
 * @file
 * Contains component.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function component_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the component module.
    case 'help.page.component':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function component_theme() {
  $theme = [];
  $theme['component'] = [
    'render element' => 'elements',
    'file' => 'component.page.inc',
    'template' => 'component',
  ];

  $theme['component_content_add_list'] = [
    'render element' => 'content',
    'variables' => ['content' => NULL],
    'file' => 'component.page.inc',
  ];
  return $theme;
}

function component_preprocess_page(&$variables) {
  if ($component = \Drupal::routeMatch()->getParameter('component')) {
    $variables['component'] = $component;
  }
}