<?php

/**
 * @file
 * Contains clutch.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\field\Entity\FieldStorageConfig;
use Drupal\field\Entity\FieldConfig;

/**
 * Implements hook_help().
 */
function clutch_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the clutch module.
    case 'help.page.clutch':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Poetic Systems awesome website conversion module.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_install().
 */
function clutch_install() {
  $bundle = entity_create('component_type', array(
    'id' => 'component_view_reference',
    'label' => 'Component View Reference',
    'revision' => FALSE,
  ));
  $bundle->save();
  //TODO: need to automate creating field and attach to
  //component_view_reference
}
