; This file was auto-generated by drush make
core = 8.x
api = 2

; Core
projects[drupal][patch][0] = "https://www.drupal.org/files/issues/2635712-20.patch"
; Modules
projects[address][subdir] = "contrib"
projects[address][version] = "1.0-rc4"

projects[admin_toolbar][subdir] = "contrib"
projects[admin_toolbar][version] = "1.19"

projects[advagg][subdir] = "contrib"
projects[advagg][version] = "2.4"

projects[coffee][subdir] = "contrib"
projects[coffee][version] = "1.0-beta2"

projects[ctools][subdir] = "contrib"
projects[ctools][version] = "3.0-beta2"

projects[devel][subdir] = "contrib"
projects[devel][version] = "1.0-rc2"

projects[entity_reference_revisions][subdir] = "contrib"
projects[entity_reference_revisions][version] = "1.2"

projects[field_group][subdir] = "contrib"
projects[field_group][download][branch] = "1.x-dev"
projects[field_group][download][revision] = "8a123a5"
projects[field_group][download][type] = "git"

projects[filefield_paths][subdir] = "contrib"
projects[filefield_paths][download][branch] = "1.x-dev"
projects[filefield_paths][download][revision] = "410c6b9"
projects[filefield_paths][download][type] "git"

projects[honeypot][subdir] = "contrib"
projects[honeypot][version] = "1.24"

projects[iframe][subdir] = "contrib"
projects[iframe][version] = "1.7"

projects[imce][subdir] = "contrib"
projects[imce][version] = "1.5"

projects[linkit][subdir] = "contrib"
projects[linkit][version] = "4.3"

projects[metatag][subdir] = "contrib"
projects[metatag][version] = "1.0"

projects[migrate_plus][subdir] = "contrib"
projects[migrate_plus][version] = "^2.0"

projects[migrate_tools][subdir] = "contrib"
projects[migrate_tools][version] = "^2.0"

projects[page_manager][subdir] = "contrib"
projects[page_manager][version] = "4.0-beta1"

projects[panels][subdir] = "contrib"
projects[panels][version] = "4.0-beta1"

projects[paragraphs][subdir] = "contrib"
projects[paragraphs][version] = "1.1"

projects[pathauto][subdir] = "contrib"
projects[pathauto][version] = "1.0-rc1"

projects[path_redirect_import][subdir] = "contrib"
projects[path_redirect_import][version] = "1.0-beta1"

projects[purge][subdir] = "contrib"
projects[purge][version] = "3.0-beta6"

projects[redirect][subdir] = "contrib"
projects[redirect][version] = "^1.0@alpha"

projects[special_menu_items][subdir] = "contrib"
projects[special_menu_items][download][branch] = "1.x-dev"
projects[special_menu_items][download][revision] = "ee6c072"
projects[special_menu_items][download][type] = "git"

projects[token][subdir] = "contrib"
projects[token][version] = "1.0-rc1"

projects[twig_tweak][subdir] = "contrib"
projects[twig_tweak][version] = "1.6"

projects[webform][subdir] = "contrib"
projects[webform][version] = "5.0-beta12"

projects[xmlsitemap][subdir] = "contrib"
projects[xmlsitemap][version] = "1.0-alpha2"
