; This file was auto-generated by drush make
core = 8.x
api = 2

; Core
; Modules
projects[admin_toolbar][subdir] = "contrib"
projects[admin_toolbar][version] = "1.14"

projects[bg_image_formatter][subdir] = "contrib"
projects[bg_image_formatter][version] = "1.x-dev"
projects[bg_image_formatter][download][revision] = "9e15fa0"
projects[bg_image_formatter][download][type] = "git"

projects[coffee][subdir] = "contrib"
projects[coffee][version] = "1.0-beta1"

projects[contact_storage][subdir] = "contrib"
projects[contact_storage][version] = "1.0-beta2"

projects[ctools][subdir] = "contrib"
projects[ctools][version] = "3.0-alpha23"

projects[devel][subdir] = "contrib"
projects[devel][download][branch] = "1.x-dev"
projects[devel][download][revision] = "c0b5c5f"
projects[devel][download][type] = "git"

projects[entity_reference_revisions][subdir] = "contrib"
projects[entity_reference_revisions][version] = "1.0-rc4"

projects[iframe][subdir] = "contrib"
projects[iframe][version] = "1.3"

projects[imce][subdir] = "contrib"
projects[imce][version] = "1.0"

projects[linkit][subdir] = "contrib"
projects[linkit][version] = "4.1"

projects[metatag][subdir] = "contrib"
projects[metatag][version] = "1.0-beta5"

projects[migrate_plus][subdir] = "contrib"
projects[migrate_plus][version] = "1.0-beta1"

projects[paragraphs][subdir] = "contrib"
projects[paragraphs][version] = "1.0-rc4"

projects[pathauto][subdir] = "contrib"
projects[pathauto][version] = "1.0-alpha2"

projects[redirect][type] = module
projects[redirect][subdir] = "contrib"
projects[redirect][download][type] = git
projects[redirect][download][url] = https://github.com/md-systems/redirect.git
projects[redirect][download][branch] = "8.x-1.x"

projects[s3fs][subdir] = "contrib"
projects[s3fs][download][branch] = "2.x-dev"
projects[s3fs][download][revision] = "bc925ea"
projects[s3fs][download][type] = "git"
projects[s3fs][patch][0] = "https://www.drupal.org/files/issues/s3fs-use_drush_translation_function-2679887-4-8.0.0.patch"

projects[simple_sitemap][subdir] = "contrib"
projects[simple_sitemap][version] = "2.2"

projects[special_menu_items][subdir] = "contrib"
projects[special_menu_items][download][branch] = "1.x-dev"
projects[special_menu_items][download][revision] = "ee6c072"
projects[special_menu_items][download][type] = "git"

projects[token][subdir] = "contrib"
projects[token][version] = "1.0-alpha2"
