<?php

/**
 * @file
 * Contains custom_page.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\field\Entity\FieldConfig;
use Drupal\field\Entity\FieldStorageConfig;

/**
 * Implements hook_help().
 */
function custom_page_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the custom_page module.
    case 'help.page.custom_page':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Create one of page. Replacement for Page Manager.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function custom_page_theme() {
	$theme = [];
	$theme['custom_page'] = [
		'render element' => 'elements',
		'file' => 'custom_page.page.inc',
		'template' => 'custom_page'
	];
	return $theme;
}

/**
 * Implements hook_preprocess_page().
 */
function custom_page_preprocess_page(&$variables) {
  if ($custom_page = \Drupal::routeMatch()->getParameter('custom_page')) {
    $variables['custom_page'] = $custom_page;
  }
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function custom_page_theme_suggestions_custom_page(array $variables) {
  $suggestions = array();
  $custom_page = $variables['elements']['#custom_page'];
  $suggestions[] = 'custom_page__' . strtolower($custom_page->getName());
  return $suggestions;
}